name: weddell_polynya
channels:
  - conda-forge
  - defaults
dependencies:
  - asn1crypto=0.24.0=py37_1003
  - basemap=1.2.0=py37h9622e30_3
  - basemap-data-hires=1.2.0=0
  - bzip2=1.0.6=h1de35cc_1002
  - ca-certificates=2019.6.16=hecc5488_0
  - certifi=2019.6.16=py37_0
  - cffi=1.12.3=py37hccf1714_0
  - chardet=3.0.4=py37_1003
  - cmocean=2.0=py_0
  - cryptography=2.7=py37h212c5bf_0
  - cycler=0.10.0=py_1
  - freetype=2.10.0=h24853df_0
  - geographiclib=1.49=py_0
  - geos=3.7.1=h0a44026_1000
  - h5py=2.9.0=nompi_py37h35dc34b_1102
  - hdf5=1.10.4=nompi_h0cbb7df_1106
  - idna=2.8=py37_1000
  - kiwisolver=1.1.0=py37h770b8ee_0
  - libblas=3.8.0=7_openblas
  - libcblas=3.8.0=7_openblas
  - libcxx=8.0.0=2
  - libcxxabi=8.0.0=2
  - libffi=3.2.1=h6de7cb9_1006
  - libgfortran=3.0.1=0
  - liblapack=3.8.0=7_openblas
  - libpng=1.6.37=h2573ce8_0
  - matplotlib=3.1.0=py37_1
  - matplotlib-base=3.1.0=py37h3a684a6_1
  - ncurses=6.1=h0a44026_1002
  - numpy=1.16.4=py37h6b0580a_0
  - openblas=0.3.5=h436c29b_1001
  - openssl=1.1.1b=h01d97ff_2
  - pandas=0.24.2=py37h86efe34_0
  - pip=19.1.1=py37_0
  - proj4=5.2.0=h6de7cb9_1003
  - pycparser=2.19=py37_1
  - pyopenssl=19.0.0=py37_0
  - pyparsing=2.4.0=py_0
  - pyproj=1.9.6=py37h01d97ff_1002
  - pyshp=2.1.0=py_0
  - pysocks=1.7.0=py37_0
  - python=3.7.3=h0d93f26_0
  - python-dateutil=2.8.0=py_0
  - pytz=2019.1=py_0
  - readline=7.0=hcfe32e1_1001
  - requests=2.22.0=py37_0
  - scipy=1.3.0=py37hab3da7d_0
  - seawater=3.3.4=py_1
  - setuptools=41.0.1=py37_0
  - six=1.12.0=py37_1000
  - sqlite=3.28.0=h9721f7c_0
  - tk=8.6.9=h2573ce8_1002
  - tornado=6.0.3=py37h01d97ff_0
  - urllib3=1.24.3=py37_0
  - wheel=0.33.4=py37_0
  - xarray=0.12.1=py_0
  - xz=5.2.4=h1de35cc_1001
  - zlib=1.2.11=h1de35cc_1004
  - pip:
    - cftime==1.0.3.4
    - circles==0.1
    - ecmwf-api-client==1.5.4
    - gsw==3.3.1
    - netcdf4==1.5.1.2
prefix: /Applications/anaconda/envs/weddell_polynya

